dist: xenial
language: python
python:
    - "3.6"
    - "3.7"
before_script:
    - pylint knowlift tests --exit-zero
    - flake8 --statistics
install:
    - pip install -r requirements.txt
script:
    - coverage run -m unittest discover
after_success:
    - codecov
